const profilesDict = [
  'Seguidores',
  'Siguiendo',
  'Ver más',
  'Popularidad',
  '{1} Lugar',
  'Recomendaciones',
  '{1} Totales',
  'Seguir',
  'Siguiendo',
  'Guardar',
  'Ver tarjeta',
  'Recomendar',
  'ver',
  'Recomendado',
  '{1} Veces',
  'Pasaporte',
  '{1} Check In',
  'Eres Cliente',
  'Hacer Check-In',
  'Link Business',
  'Llamar',
  'Mensajes',
  'Correo',
  'Mapa',
  'Web',
  'mostrar completo',
  '{1} te recomienda',
  'Ver todo',
  'Distinciones',
  'Cumplidos',
  'Productos',
  'Noticias',
  'Historias destacadas',
  'Publicaciones',
  'Galería',
  'Recomendaciones',
];

export default profilesDict;
