const AdminsDict = [
  'Publicaciones',
  'Administrar',
  'Información',
  'Clientes',
  'Propietario',
  'Buzón',
  'Configuración',
  'Estados',
  'Noticias',
  'Promociones',
  'Recomendaciones',
  'Alguien sabe?',
  'Eventos',
  'Cupones',
  'Crear',
  'Borradores',
  'Programadas',
  'Mes',
  'Categoría',
  '{1} reproducciones',
  '{1} comentarios',
  'Eliminar publicación',
  'Ocultar del perfil',
  'Todo',
  'Amigos etiquetados',
  'Ubicación',
  'Les recomiendo',
  'Estados',
  'Destacados',
  'Ajustes',
  'Ver los {1} comentarios',
  'Las preguntas hechas por usuarios que buscan información sobre ti.',
  '...más',
  'menos',
  'Año',
  'Enviados',
  'Mi cuponera',
  'Buscar',
  'Tarjeta',
  'R.A',
  'Tienda',
  'Mi Perfil',
  'Mensaje automático',
  'Activado',
  'Desactivado',
  'Activa tu mensaje para que las personas puedan verlo cuando compartas tu tarjeta.',
  'Editar',
  'Guardar',
  'Crea tu video',
  'Abrir galería',
  'Impresión de Tarjetas',
  'Beneficios',
  'Nos aseguramos de que tus tarjetas My-Link se vean tan bien en papel como se ven en tu pantalla.',
  'Imprimimos tus tarjetas My-Link que te encantarán y a un precio accesible.',
  'Puedes tener tu tarjeta Personal o Business con su diseño característico y sus respectivos beneficios que incluyen:',
  '\u2022 Realidad Aumentada',
  '\u2022 Código QR(Que registra su Link)',
  'Entregamos el paquete de 500 impresiones a tu casa entre 3 y 5 días después, o puedes elegir la opción de envio exprés.',
  'Categoría de Tarjeta',
  'Personal',
  'Business',
  'Cantidad a pagar',
  'Tamaño',
  'Envío',
  'Devolución',
  'Comprar por ',
  'Agregar al carrito',
  'Foto de perfil',
  'Nombre',
  'Eslogan',
  'Escribe aquí el nombre',
  'Escribe aquí tu eslogan',
  'Datos',
  'Horario',
  'Contacto',
  'Aniversario',
  'Correo',
  'Teléfono',
  'Celular',
  'Mensajes',
  'Productos',
  'Aún no tienes productos',
  '¡Selecciona el ícono "Agregar" y agrega tus productos!',
  'Listado de productos',
  'Agregar',
  'Editar categoría',
  'Eliminar categoría',
  'Servicios',
  'Listado de servicios',
  'Selecciona tus servicios',
  'Clientes',
  'Premium',
  'Eliminar',
  'Enviar cupón',
  'Mensaje',
  'Llamar',
  'Te han recomendado {1} personas en este día',
  'Titanium',
  'Platino',
  'Oro',
  'Plata',
  'Bronce',
  'Rankin',
  'Las recomendaciones subirán tu rankin',
  '¡Procura que tus clientes te recomienden!',
  'Ver todas',
  'Más recientes',
  'Agradecer',
  'Te recomiendo con:',
  'Ver más',
  'Ver menos',
  'Top',
  'Eliminar de lista',
  'Vista distinción',
  'Vista contacto',
  'Roles',
  'Administrador',
  'Editor',
  'Puestos',
  'Verificar colaborador',
  'Cambiar puesto',
  'Empleado del mes',
  'Eliminar colaborador',
  'Agrega un comentario',
  'Volver a mis mensajes',
  'Vinculación',
  'Matriz',
  'Sucursal',
  'Plaza',
  'Agrega tarjetas Business para tener {1}',
  'Afiliar a una matriz',
  'Agrega sucursal',
  'Unirse a plaza',
  'Ayuda',
  'Descripción',
  'Mis datos',
  'Dirección',
  'Perfil Social',
  'Redes',
  'Galería',
  'MyLink, Facebook, Instagram...',
  'Tus fotos, videos, historias...',
  'Ayuda, comunidad y más...',
  'Tus recomendados...',
  'Documentos',
  'Pasaporte',
  'Identificación personal',
  'Licencia de conducir',
  'Cédula profesional',
  'Currículum',
  'Privacidad',
  'Perfiles',
  'Seguidores',
  'Edita el perfil para compartir tu link de manera rápida',
  'General',
  'Familia',
  'Amigos',
  'Cliente',
  'Personalizado',
  'Agregar perfil',
  'Cambiar nombre',
  'Eliminar perfil',
  'Videollamadas',
  'Siguiendo',
  'Seguir',
  'Dejar de seguir',
  'Profesional',
  'Educación',
  'Trabajo',
  'Nombre de la escuela',
  'Grado adquirido',
  'Estudios finalizados',
  'Fecha de inicio',
  'Fecha de finalización',
  'Nombre del lugar de trabajo',
  'Cargo',
  'Actualmente trabajando aquí',
  'Solicita al negocio que te verifique como uno de sus empleados',
  'Solicitar',
  'Solicitado',
  'Cumplidos',
  'Ver cumplidos',
  'Vista cumplido',
];

export default AdminsDict;
