const users = {
  andyxz8823: {
    foto: 'https://randomuser.me/api/portraits/women/37.jpg',
    pais: 'ar',
    nombre: 'Andrea',
    apellido_paterno: 'Baños',
    link: 'andyxz8823',
  },
  ifahandsome8823: {
    foto: 'https://randomuser.me/api/portraits/men/47.jpg',
    pais: 'tn',
    nombre: 'Ifahad',
    apellido_paterno: '',
    link: 'ifahandsome8823',
  },
  tabata0039: {
    foto: 'https://randomuser.me/api/portraits/women/75.jpg',
    pais: 'es',
    nombre: 'Tabata',
    apellido_paterno: 'Casamadrid',
    link: 'tabata0039',
  },
  bishito0948: {
    foto: 'https://randomuser.me/api/portraits/men/37.jpg',
    pais: 'ar',
    nombre: 'Benicio',
    apellido_paterno: 'Acosta',
    link: 'bishito0948',
  },
  julo123: {
    foto: 'https://randomuser.me/api/portraits/men/57.jpg',
    pais: 'mx',
    nombre: 'Juan',
    apellido_paterno: 'López',
    link: 'julo123',
  },
  maor8695: {
    foto: 'https://randomuser.me/api/portraits/women/39.jpg',
    pais: 'pe',
    nombre: 'Mariana',
    apellido_paterno: 'Ortiz',
    link: 'maor8695',
  },
  lara9565: {
    foto: 'https://randomuser.me/api/portraits/women/45.jpg',
    pais: 'cr',
    nombre: 'Laura',
    apellido_paterno: 'Ramirez',
    link: 'lara9565',
  },
  anib3471: {
    foto: 'https://randomuser.me/api/portraits/women/22.jpg',
    pais: 'mx',
    nombre: 'Andrea',
    apellido_paterno: 'Ibañez',
    link: 'anib3471',
  },
  peja245: {
    foto: 'https://randomuser.me/api/portraits/men/17.jpg',
    pais: 'fr',
    nombre: 'Pedro',
    apellido_paterno: 'Jaimes',
    link: 'peja245',
  },
  anaje0234: {
    foto: 'https://randomuser.me/api/portraits/women/19.jpg',
    pais: 'pr',
    nombre: 'Ana',
    apellido_paterno: 'Jaimes',
    link: 'anaje0234',
  },
  riva1258: {
    foto: 'https://randomuser.me/api/portraits/men/28.jpg',
    pais: 'mx',
    nombre: 'Ricardo',
    apellido_paterno: 'Hernández',
    link: 'riva1258',
  },
  abhe5895: {
    foto: 'https://randomuser.me/api/portraits/women/23.jpg',
    pais: 'it',
    nombre: 'Abril',
    apellido_paterno: 'Hernández',
    link: 'abhe5895',
  },
  pajai3467: {
    foto: 'https://randomuser.me/api/portraits/women/24.jpg',
    pais: 'es',
    nombre: 'Pamela',
    apellido_paterno: 'Jaimes',
    link: 'pajai3467',
  },
  pasmi4830: {
    foto: 'https://randomuser.me/api/portraits/women/21.jpg',
    pais: 'pr',
    nombre: 'Patricia',
    apellido_paterno: 'Smith',
    link: 'pasmi4830',
  },
  abhe3009: {
    foto: 'https://randomuser.me/api/portraits/women/25.jpg',
    pais: 'gr',
    nombre: 'Abril',
    apellido_paterno: 'Hernández',
    link: 'abhe3009',
  },
  aleva5241: {
    foto: 'https://randomuser.me/api/portraits/women/13.jpg',
    pais: 'be',
    nombre: 'Alejandra',
    apellido_paterno: 'Varela',
    link: 'aleva5241',
  },
  laurod1892: {
    foto: 'https://randomuser.me/api/portraits/women/5.jpg',
    pais: 'us',
    nombre: 'Laura',
    apellido_paterno: 'Rodriguez',
    link: 'laurod1892',
  },
  juanber1258: {
    foto: 'https://randomuser.me/api/portraits/women/7.jpg',
    pais: 'pr',
    nombre: 'Juana',
    apellido_paterno: 'Bermudez',
    link: 'juanber1258',
  },
  carlop2357: {
    foto: 'https://randomuser.me/api/portraits/men/37.jpg',
    pais: 'ar',
    nombre: 'Carlos',
    apellido_paterno: 'López',
    link: 'carlop2357',
  },
  juago4389: {
    foto: 'https://randomuser.me/api/portraits/women/8.jpg',
    pais: 'pe',
    nombre: 'Juanita',
    apellido_paterno: 'Gomez',
    link: 'juago4389',
  },
  lauleo2112: {
    foto: 'https://randomuser.me/api/portraits/women/11.jpg',
    pais: 'mx',
    nombre: 'Laura',
    apellido_paterno: 'Leon',
    link: 'lauleo2112',
  },
  horvil3765: {
    foto: 'https://randomuser.me/api/portraits/men/32.jpg',
    pais: 'ar',
    nombre: 'timecio',
    apellido_paterno: 'Villalobos',
    link: 'horvil3765',
  },
  mabe4930: {
    foto: 'https://randomuser.me/api/portraits/women/32.jpg',
    pais: 'ar',
    nombre: 'Maria',
    apellido_paterno: 'Benitez',
    link: 'mabe4930',
  },
  camo4849: {
    foto: 'https://randomuser.me/api/portraits/women/48.jpg',
    pais: 'ar',
    nombre: 'Camila',
    apellido_paterno: 'Morales',
    link: 'camo4849',
  },
  abis0111: {
    foto: 'https://randomuser.me/api/portraits/women/97.jpg',
    pais: 'mx',
    nombre: 'Abril',
    apellido_paterno: 'Isabel',
    link: 'abis0111',
  },
  tivil3765: {
    foto: 'https://randomuser.me/api/portraits/men/32.jpg',
    pais: 'ar',
    nombre: 'timecio',
    apellido_paterno: 'Villalobos',
    link: 'tivil3765',
  },
  mape4398: {
    foto: 'https://randomuser.me/api/portraits/women/85.jpg',
    pais: 'cr',
    nombre: 'Mariela',
    apellido_paterno: 'Perez',
    link: 'mape4398',
  },
  lauva3293: {
    foto: 'https://randomuser.me/api/portraits/women/50.jpg',
    pais: 'mx',
    nombre: 'Laura',
    apellido_paterno: 'Varela',
    link: 'lauva3293',
  },
  danpe4398: {
    foto: 'https://randomuser.me/api/portraits/women/55.jpg',
    pais: 'cr',
    nombre: 'Daniela',
    apellido_paterno: 'Perez',
    link: 'danpe4398',
  },
  molo3944: {
    foto: 'https://randomuser.me/api/portraits/women/95.jpg',
    pais: 'be',
    nombre: 'Mónica',
    apellido_paterno: 'López',
    link: 'molo3944',
  },
  danra2598: {
    foto: 'https://randomuser.me/api/portraits/men/75.jpg',
    pais: 'ar',
    nombre: 'Daniel',
    apellido_paterno: 'Ramirez',
    link: 'danra2598',
  },
  cartelbi: {
    foto: 'https://i.picsum.photos/id/650/200/200.jpg',
    pais: 'mx',
    nombre: 'Cartel Bi',
    link: 'cartelbi',
  },
  eonmarketing: {
    foto: 'https://i.picsum.photos/id/350/200/200.jpg',
    pais: 'mx',
    nombre: 'EON Marketing',
    link: 'eonmarketing',
  },
  enfokepublicidad: {
    foto: 'https://i.picsum.photos/id/450/200/200.jpg',
    pais: 'mx',
    nombre: 'Enfoke Publicidad',
    link: 'enfokepublicidad',
  },
  itlatinoamericano: {
    foto: 'https://i.picsum.photos/id/100/200/200.jpg',
    pais: 'mx',
    nombre: 'Instituto Tecnológico Latinoamericano',
    link: 'itlatinoamericano',
  },
  itpachuca: {
    foto: 'https://i.picsum.photos/id/200/200/200.jpg',
    pais: 'mx',
    nombre: 'Instituto Tecnológico de Pachuca',
    link: 'itpachuca',
  },
  uaehidalgo: {
    foto: 'https://i.picsum.photos/id/300/200/200.jpg',
    pais: 'mx',
    nombre: 'Universidad Autonoma del Estado Hidalgo',
    link: 'uaehidalgo',
  },
};

const productsResponse = {
  id: 'string',
  data: {
    personal: [
      {
        id: 'a1',
        img: 'https://i.picsum.photos/id/898/200/200.jpg',
        description: 'This is an awesome promotion 1.',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'b2',
        img: 'https://i.picsum.photos/id/532/200/200.jpg',
        description: 'This is an awesome promotion 2.',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 1,
      },
      {
        id: 'f6',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/155/200/200.jpg',
        description: 'My-Link A',
        price: 600.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 1,
      },
      {
        id: 'i9',
        icon: 'personal',
        img: 'https://i.picsum.photos/id/43/200/200.jpg',
        description: 'My-Link VIP',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 2,
      },
      {
        id: 'j10',
        icon: 'personal',
        img: 'https://i.picsum.photos/id/53/200/200.jpg',
        description: 'My-Link A',
        price: 600.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 3,
      },
      {
        id: 'k11',
        icon: 'personal',
        img: 'https://i.picsum.photos/id/63/200/200.jpg',
        description: 'My-Link B',
        price: 700.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'l12',
        icon: 'personal',
        img: 'https://i.picsum.photos/id/73/200/200.jpg',
        description: 'My-Link C',
        price: 200.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 2,
      },
    ],
    business: [
      {
        id: 'c3',
        img: 'https://i.picsum.photos/id/127/200/200.jpg',
        description: 'This is an awesome promotion 3.',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'd4',
        img: 'https://i.picsum.photos/id/135/200/200.jpg',
        description: 'This is an awesome promotion 4.',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 2,
      },
      {
        id: 'm13',
        icon: 'star',
        img: 'https://i.picsum.photos/id/44/200/200.jpg',
        description: 'My-Link VIP',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'n14',
        icon: 'star',
        img: 'https://i.picsum.photos/id/54/200/200.jpg',
        description: 'My-Link A',
        price: 600.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 3,
      },
      {
        id: 'o15',
        icon: 'star',
        img: 'https://i.picsum.photos/id/64/200/200.jpg',
        description: 'My-Link B',
        price: 700.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'p16',
        icon: 'star',
        img: 'https://i.picsum.photos/id/74/200/200.jpg',
        description: 'My-Link C',
        price: 200.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 2,
      },
    ],
    vip: [
      {
        id: 'e5',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/100/200/200.jpg',
        description: 'My-Link VIP',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'h8',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/358/200/200.jpg',
        description: 'My-Link C',
        price: 200.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 2,
      },
      {
        id: 'g7',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/200/200/200.jpg',
        description: 'My-Link B',
        price: 700.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'q17',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/45/200/200.jpg',
        description: 'My-Link VIP',
        price: 35.85,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 3,
      },
      {
        id: 'r18',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/55/200/200.jpg',
        description: 'My-Link A',
        price: 125.45,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 1,
      },
      {
        id: 's19',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/65/200/200.jpg',
        description: 'My-Link B',
        price: 456.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 2,
      },
      {
        id: 't20',
        icon: 'vip',
        img: 'https://i.picsum.photos/id/75/200/200.jpg',
        description: 'My-Link C',
        price: 148.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 3,
      },
    ],
    printing: [
      {
        id: 'e5',
        icon: 'card',
        img: 'https://i.picsum.photos/id/42/200/200.jpg',
        description: 'My-Link VIP',
        price: 500.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'f6',
        icon: 'card',
        img: 'https://i.picsum.photos/id/52/200/200.jpg',
        description: 'My-Link A',
        price: 600.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 2,
      },
      {
        id: 'g7',
        icon: 'card',
        img: 'https://i.picsum.photos/id/62/200/200.jpg',
        description: 'My-Link B',
        price: 700.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'single',
        monthsOfDuration: 1,
      },
      {
        id: 'h8',
        icon: 'card',
        img: 'https://i.picsum.photos/id/72/200/200.jpg',
        description: 'My-Link C',
        price: 200.0,
        benefitsSummary:
          'Ser un usuario VIP en My-Link te hara tener una experiencia más exclusiva y podrás disfrutar de grandes privilegios como:',
        benefits: [
          'Solo podrán solicitar tu Link otros usuarios VIP.',
          'Podrás registrar a un usuario de My Link como representante tuyo para que puedan contactarte a través de él.',
          'Tendras acceso a un modo privado',
          'Incluye 10 GB de almacenamiento en la nube.',
          'Sorprendete con el diseño exclusivo en los módulos personales.',
          'Gana puntos en tu saldo My-Link cuando se te excluya de un grupo de chat.',
        ],
        paymentType: 'monthly',
        monthsOfDuration: 3,
      },
    ],
  },
  subcollection: {},
};

const promotionsResponse = {
  id: 'string',
  data: {
    items: [
      productsResponse.data.personal[2],
      productsResponse.data.personal[4],
      productsResponse.data.personal[6],
      productsResponse.data.business[1],
      productsResponse.data.business[3],
      productsResponse.data.business[5],
      productsResponse.data.vip[2],
      productsResponse.data.vip[4],
      productsResponse.data.vip[6],
    ],
  },
  subcollection: {},
};

const suggestionsResponse = {
  id: 'string',
  data: {
    items: [
      productsResponse.data.vip[2],
      productsResponse.data.vip[4],
      productsResponse.data.vip[6],
      productsResponse.data.personal[2],
      productsResponse.data.personal[4],
      productsResponse.data.personal[6],
      productsResponse.data.business[1],
      productsResponse.data.business[3],
      productsResponse.data.business[5],
    ],
  },
  subcollection: {},
};

const userPurchasesResponse = {
  id: 'string',
  data: {
    items: [
      {
        ...productsResponse.data.personal[4],
        purchaseDate: {day: 28, month: 10, year: 2020},
        expiration: {day: 1, month: 11, year: 2020},
        paymentMethod: {type: 'credit card', card: 'Master Card', number: 4575},
      },
      {
        ...productsResponse.data.business[3],
        purchaseDate: {day: 28, month: 10, year: 2020},
        expiration: {day: 1, month: 11, year: 2020},
        paymentMethod: {type: 'credit card', card: 'Master Card', number: 4575},
      },
      {
        ...productsResponse.data.vip[4],
        purchaseDate: {day: 28, month: 10, year: 2020},
        expiration: {day: 1, month: 11, year: 2020},
        paymentMethod: {type: 'credit card', card: 'Master Card', number: 4575},
      },
      {
        ...productsResponse.data.business[1],
        purchaseDate: {day: 28, month: 10, year: 2020},
        expiration: {day: 1, month: 11, year: 2020},
        paymentMethod: {type: 'credit card', card: 'Master Card', number: 4575},
      },
    ],
  },
  subcollection: {},
};

const faqsResponse = {
  id: 'string',
  data: {
    faqs: [
      {
        question: 'Problemas con mi pago',
        answer: 'Estamos trabajando en ello...',
      },
      {
        question: 'Problemas con mi producto',
        answer: 'Estamos trabajando en ello...',
      },
      {
        question: 'Problemas con mi pago',
        answer: 'Estamos trabajando en ello...',
      },
      {
        question: 'Problemas con mi producto',
        answer: 'Estamos trabajando en ello...',
      },
      {
        question: 'Problemas con mi pago',
        answer: 'Estamos trabajando en ello...',
      },
      {
        question: 'Problemas con mi producto',
        answer: 'Estamos trabajando en ello...',
      },
    ],
  },
  subcollection: {},
};

const myBalanceResponse = {
  id: 'string',
  data: {
    balance: {
      total: 2319.46,
      currency: 'MXN',
    },
  },
  subcollection: {},
};

const myCardsResponse = {
  id: 'string',
  data: {
    cards: [
      {
        number: '5874562123569874',
        type: 'VISA',
        month: '',
        year: '',
        cvc: '',
        owner: '',
        country: 'México',
        line1: '',
        line2: '',
        zip: '',
        city: '',
        state: '',
      },
      {
        number: '4125458963257895',
        type: 'VISA',
        month: '',
        year: '',
        cvc: '',
        owner: '',
        country: 'México',
        line1: '',
        line2: '',
        zip: '',
        city: '',
        state: '',
      },
      {
        number: '4152365247895126',
        type: 'VISA',
        month: '',
        year: '',
        cvc: '',
        owner: '',
        country: 'México',
        line1: '',
        line2: '',
        zip: '',
        city: '',
        state: '',
      },
    ],
  },
  subcollection: {},
};

const transfersResponse = {
  id: 'string',
  data: {
    transfers: [
      {
        user: users.abhe3009,
        sent: true,
      },
      {
        user: users.camo4849,
        sent: false,
      },
      {
        user: users.horvil3765,
        sent: true,
      },
      {
        user: users.abhe5895,
        sent: false,
      },
      {
        user: users.andyxz8823,
        sent: true,
      },
      {
        user: users.peja245,
        sent: false,
      },
      {
        user: users.lauleo2112,
        sent: true,
      },
      {
        user: users.laurod1892,
        sent: false,
      },
      {
        user: users.tabata0039,
        sent: false,
      },
    ],
  },
  subcollection: {},
};

export {
  productsResponse,
  promotionsResponse,
  suggestionsResponse,
  userPurchasesResponse,
  faqsResponse,
  myBalanceResponse,
  myCardsResponse,
  transfersResponse,
};
