const storeDict = [
  'Categorías',
  'Billetera',
  'Mi Carrito',
  'Compras',
  'Ayuda',
  'Sugerencia para ti',
  'Personal',
  'Business',
  'VIP',
  'Mis tarjetas',
  'Saldo My-Link',
  'Tarjeta',
  'Asociar tarjeta de credito o débito',
  'Mi saldo',
  'Transferencias',
  'Disponible',
  'Agregar saldo',
  'Enviar bono',
  'Solicitar bono',
  'Mis bonos',
  'Enviaste un bono',
  'Recibiste un bono',
  '{1} Productos',
  'Total',
  'Agregar saldo My - Link',
  'Solo puedes agregar una cantidad entre $1 y $50 dólares en una sola transacción de saldo My-Link, con un máximo de 2 transacciones de $25 dólares para un total de $50 dólares de recarga cada 24 horas.',
  'Número de tarjeta',
  'Nombre del titular',
  'país',
  'Linea 1 de la dirección',
  'Linea 2 de la dirección',
  'Código postal',
  'Ciudad',
  'Estado / Provincia',
  'Asociar tarjeta',
  'Producto agregado a tu carrito',
  'Por favor indica una cantidad para tu saldo',
  'Por favor selecciona una tarjeta',
	'Por favor escribe el número de la tarjeta',
	'Continuar',
];

export default storeDict;
